FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore "src/PosOptimizer.Api/PosOptimizer.Api.csproj"
RUN dotnet publish "src/PosOptimizer.Api/PosOptimizer.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "PosOptimizer.Api.dll"]